#!/bin/bash
##  sbatch launching script template                May 2014  MKuiper
## -A generic script to launch a series of production namd runs
## on the Avoca bluegene cluster at vlsci. 
#--------------------------------------------------------------- 
#         Make all changes in "master_config_file"             #
#     -you shouldn't have to change anything in here!          #
#---------------------------------------------------------------
#-- Sbatch parameters:------------------------------------------
#-- the X values will be substituted with a values from the master_config_file 
#-- when you populate job directories with ./mdwf -p 

#SBATCH --nodes=2
#SBATCH --time=24:0:0
#SBATCH --account=VR0021

ntpn=8         # number of tasks per node: 
ppn=8          # processors per node: 

production_script=namd_production_script.conf

module load namd-xl-pami-smp/2.10                # module file:
module load python-fe/2.7.3  # python module file

#--------------------------------------------------------------------------------
# python script for preprocessing data

 python prejob_processing.py $SLURM_JOBID -production

# prevent job from running if pausejob is present

if [ -f pausejob ]; then
 exit
fi

# run optimization job.
 srun  --ntasks-per-node $ntpn  namd2 +ppn $ppn $production_script >temp_working_outputfile.out 2>temp_working_errorsfile.err;

# --------------------------------------------------------------------------------------------
# python script for postprocessing data

 python postjob_processing.py $SLURM_JOBID -production

# prevent job from running if pausejob is present
if [ -f pausejob ]; then
 exit
fi

# launch next phase: 
 sbatch sbatch_production_script 

